import type { IAddressLineDataCollection } from "./IAddressLineDataCollection";

/**
 * Physical postal address data returned by the iMIS API, corresponding to the
 * `AddressData` contract. Embedded within {@link IFullAddressData}.
 *
 * @property $type - iMIS type discriminator.
 * @property AddressId - Unique identifier for this address record within iMIS.
 * @property AddressLines - Collection of free-form address line strings (street lines).
 * @property CityName - City or municipality name.
 * @property CountryCode - ISO 3166-1 alpha-2 or iMIS country code.
 * @property CountryName - Human-readable country name.
 * @property CountrySubEntityCode - State, province, or region code.
 * @property CountrySubEntityName - Human-readable state/province name.
 * @property CountyName - County name, if applicable.
 * @property FullAddress - Pre-formatted multi-line address string generated by iMIS.
 * @property NationalGovernmentDistrict - Congressional or government district, if applicable.
 * @property PostalCode - ZIP or postal code.
 */
export interface IAddressData {
    $type: "Asi.Soa.Membership.DataContracts.AddressData, Asi.Contracts",
    AddressId?: string,
    AddressLines: IAddressLineDataCollection,
    CityName: string,
    CountryCode: string,
    CountryName?: string | null,
    CountrySubEntityCode?: string | null,
    CountrySubEntityName?: string | null,
    CountyName?: string | null,
    FullAddress?: string,
    NationalGovernmentDistrict?: string | null,
    PostalCode: string
}